# set the build language to python
language: python

# set the private version to 2.7
python: 
  - "3.6"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.5-dev

# install the codecov pip dependancy
#install:
#  - pip install codecov
  
# run the unit test
script:
  - python ml4_python.py<inputs.txt

# push the rresult back to codecov
#after_success:
#  - codecov
   
