# set the build language to python
language: python

# set the private version to 2.7
python: 2.7

# install the codecov pip dependancy
install:
  - pip install codecov
  
# run the unit test
script:
  - coverage run ml4_python.py

# push the rresult back to codecov
after_success:
  - codecov
   
